# Configuration file for Python modules 

hedge_rebalancer:
  # Triggers for initiating rebalancing actions
  triggers:
    # Positive trigger: underhedged pctg
    positive: 0.15
    # Negative trigger: overhedged pctg
    negative: -0.15
    # minimum value to trigger a rebalance
    min_usd: 200
hedge_monitoring:
  funding_rate_alert_threshold: -20 # in bips